package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

type PreUrl struct {
	Url    string `json:"datos"` // url
	Client *http.Client
}

type AutoGenerated []struct {
	Origen     Origen     `json:"origen"`
	Elaborado  string     `json:"elaborado"`
	Nombre     string     `json:"nombre"`
	Provincia  string     `json:"provincia"`
	Prediccion Prediccion `json:"prediccion"`
	ID         int        `json:"id"`
	Version    float64    `json:"version"`
}
type Origen struct {
	Productor string `json:"productor"`
	Web       string `json:"web"`
	Enlace    string `json:"enlace"`
	Language  string `json:"language"`
	Copyright string `json:"copyright"`
	NotaLegal string `json:"notaLegal"`
}
type ProbPrecipitacion struct {
	Value   int    `json:"value"`
	Periodo string `json:"periodo"`
}
type CotaNieveProv struct {
	Value   string `json:"value"`
	Periodo string `json:"periodo"`
}
type EstadoCielo struct {
	Value       string `json:"value"`
	Periodo     string `json:"periodo"`
	Descripcion string `json:"descripcion"`
}
type Viento struct {
	Direccion string `json:"direccion"`
	Velocidad int    `json:"velocidad"`
	Periodo   string `json:"periodo"`
}
type RachaMax struct {
	Value   string `json:"value"`
	Periodo string `json:"periodo"`
}
type Dato struct {
	Value int `json:"value"`
	Hora  int `json:"hora"`
}
type Temperatura struct {
	Maxima int    `json:"maxima"`
	Minima int    `json:"minima"`
	Dato   []Dato `json:"dato"`
}
type SensTermica struct {
	Maxima int    `json:"maxima"`
	Minima int    `json:"minima"`
	Dato   []Dato `json:"dato"`
}
type HumedadRelativa struct {
	Maxima int    `json:"maxima"`
	Minima int    `json:"minima"`
	Dato   []Dato `json:"dato"`
}
type Dia struct {
	ProbPrecipitacion []ProbPrecipitacion `json:"probPrecipitacion"`
	CotaNieveProv     []CotaNieveProv     `json:"cotaNieveProv"`
	EstadoCielo       []EstadoCielo       `json:"estadoCielo"`
	Viento            []Viento            `json:"viento"`
	RachaMax          []RachaMax          `json:"rachaMax"`
	Temperatura       Temperatura         `json:"temperatura"`
	SensTermica       SensTermica         `json:"sensTermica"`
	HumedadRelativa   HumedadRelativa     `json:"humedadRelativa"`
	UvMax             int                 `json:"uvMax,omitempty"`
	Fecha             string              `json:"fecha"`
}
type Prediccion struct {
	Dia []Dia `json:"dia"`
}

func main() {
	result, _ := GetPreUrl()
	values, _ := GetPrediction()
	for value := range values {
		fmt.Println("Parameter: ", values[value])
	}

}

func GetPreUrl() (string, error) {
	url := "https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/08001/?api_key=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZXJnaXZhcXVlQGdtYWlsLmNvbSIsImp0aSI6ImY5NDA4MTllLTM2MmMtNDQ5OC1iMDA3LTY1ODZmOWYyOGUxZCIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNjc4NzI3NTE4LCJ1c2VySWQiOiJmOTQwODE5ZS0zNjJjLTQ0OTgtYjAwNy02NTg2ZjlmMjhlMWQiLCJyb2xlIjoiIn0.rJSXW8pOwtr4T_MC1YsHWQtRJJHoiZS4YXvSJFhKwss"

	request, _ := http.NewRequest("GET", url, nil)
	request.Header.Add("cache-control", "no-cache")
	response, error := http.DefaultClient.Do(request)
	if error != nil {
		log.Println("Error connecting with AEMET")
	}

	defer response.Body.Close()
	body, error := ioutil.ReadAll(response.Body)

	if error != nil {
		log.Println("Error reading json")
	}

	preUrl := PreUrl{}
	error = json.Unmarshal(body, &preUrl)

	if error != nil {
		log.Println("Error unmarshal")
	}

	return preUrl.Url, error
}

func GetPrediction() {

}
